// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpCKqPQdkPpVWkdCS1DWTD7ltZs-K_xfM',
    appId: '1:174721385768:web:b34c25ca45c9b822313c1d',
    messagingSenderId: '174721385768',
    projectId: 'social-media-app-6cc80',
    authDomain: 'social-media-app-6cc80.firebaseapp.com',
    storageBucket: 'social-media-app-6cc80.appspot.com',
    measurementId: 'G-J586M2W6SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD7Xl61kHZAajssxwzUhbq4ldsnr53KNs',
    appId: '1:174721385768:android:1ac3256cdda430ce313c1d',
    messagingSenderId: '174721385768',
    projectId: 'social-media-app-6cc80',
    storageBucket: 'social-media-app-6cc80.appspot.com',
  );
}
